version: "1.0"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "walletService"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"